#include "LLMManager.h"
#include "../../utils/Logger.h"
#include <algorithm>
#include <chrono>
#include <fstream>
#include <sstream>

LLMManager::LLMManager() : m_defaultTemperature(0.7f), m_defaultTopP(0.9f), m_defaultMaxTokens(512), m_isGenerating(false), m_stopRequested(false) { initializeAvailableModels(); }
LLMManager::~LLMManager() { shutdown(); }
bool LLMManager::initialize() { initializeAvailableModels(); return true; }
void LLMManager::shutdown(){std::lock_guard<std::mutex> lock(m_mutex);for(auto& p:m_modelStates)if(p.second.backend)p.second.backend->unload();m_loadedModels.clear();m_modelStates.clear();m_isGenerating=false;m_stopRequested=true;}
bool LLMManager::loadModel(const std::string& n){std::lock_guard<std::mutex> lock(m_mutex);if(n.empty()||isModelLoaded(n))return !n.empty();if(!loadModelFromFile(n))return false;m_loadedModels.push_back(n);return true;}
bool LLMManager::unloadModel(const std::string& n){std::lock_guard<std::mutex> lock(m_mutex);auto it=m_modelStates.find(n);if(it==m_modelStates.end())return false;if(it->second.backend)it->second.backend->unload();m_modelStates.erase(it);m_loadedModels.erase(std::remove(m_loadedModels.begin(),m_loadedModels.end(),n),m_loadedModels.end());return true;}
bool LLMManager::isModelLoaded(const std::string& n)const{return m_modelStates.find(n)!=m_modelStates.end()&&m_modelStates.at(n).loaded;}
std::vector<std::string> LLMManager::getLoadedModels()const{std::lock_guard<std::mutex> lock(m_mutex);return m_loadedModels;}
std::string LLMManager::generate(const std::string& prompt,const std::string& modelName,float temperature,int maxTokens){std::unique_lock<std::mutex> lock(m_mutex);if(m_isGenerating||prompt.empty()||m_loadedModels.empty())return{};const std::string selected=modelName.empty()?m_loadedModels.front():modelName;auto it=m_modelStates.find(selected);if(it==m_modelStates.end()||!it->second.backend||!it->second.loaded)return{};const std::string effective=it->second.contextString.empty()?prompt:it->second.contextString+"\n"+prompt;const float temp=std::clamp(temperature,0.0f,2.0f);const int tokens=std::clamp(maxTokens,1,4096);m_isGenerating=true;m_stopRequested=false;LLMBackend* backend=it->second.backend.get();lock.unlock();std::string response=backend->generate(effective,temp,tokens);lock.lock();m_isGenerating=false;return response;}
void LLMManager::generateStreaming(const std::string& p,std::function<void(const std::string&)> onToken,std::function<void()> onComplete,const std::string& n,float t,int max){std::string r=generate(p,n,t,max);if(!r.empty()&&onToken){std::istringstream s(r);std::string token;while(s>>token){if(m_stopRequested)break;onToken(token+" ");}}if(onComplete)onComplete();}
void LLMManager::stopGeneration(){std::lock_guard<std::mutex> lock(m_mutex);m_stopRequested=true;for(auto& p:m_modelStates)if(p.second.backend)p.second.backend->stop();}
void LLMManager::resetContext(const std::string& n){std::lock_guard<std::mutex> lock(m_mutex);if(n.empty())for(auto& p:m_modelStates)p.second.contextString.clear();else if(m_modelStates.count(n))m_modelStates[n].contextString.clear();}
void LLMManager::setContext(const std::string& c,const std::string& n){std::lock_guard<std::mutex> lock(m_mutex);if(n.empty())for(auto& p:m_modelStates)p.second.contextString=c;else if(m_modelStates.count(n))m_modelStates[n].contextString=c;}
std::string LLMManager::getContext(const std::string& n)const{std::lock_guard<std::mutex> lock(m_mutex);if(n.empty()&&!m_modelStates.empty())return m_modelStates.begin()->second.contextString;auto it=m_modelStates.find(n);return it==m_modelStates.end()?std::string{}:it->second.contextString;}
LLMManager::ModelInfo LLMManager::getModelInfo(const std::string& n)const{for(const auto& m:m_availableModels)if(m.name==n)return m;return{};}
std::vector<LLMManager::ModelInfo> LLMManager::getAvailableModels()const{std::lock_guard<std::mutex> lock(m_mutex);return m_availableModels;}
float LLMManager::benchmarkModel(const std::string& n){if(!isModelLoaded(n))return 0.0f;auto start=std::chrono::steady_clock::now();if(generate("Reply with one short word: OK",n,0.1f,8).empty())return 0.0f;double s=std::chrono::duration<double>(std::chrono::steady_clock::now()-start).count();return s>0?static_cast<float>(8.0/s):0.0f;}
void LLMManager::setTemperature(float v){std::lock_guard<std::mutex> lock(m_mutex);m_defaultTemperature=std::clamp(v,0.0f,2.0f);for(auto& p:m_modelStates)p.second.temperature=m_defaultTemperature;}float LLMManager::getTemperature()const{std::lock_guard<std::mutex> lock(m_mutex);return m_defaultTemperature;}
void LLMManager::setTopP(float v){std::lock_guard<std::mutex> lock(m_mutex);m_defaultTopP=std::clamp(v,0.0f,1.0f);for(auto& p:m_modelStates)p.second.topP=m_defaultTopP;}float LLMManager::getTopP()const{std::lock_guard<std::mutex> lock(m_mutex);return m_defaultTopP;}
void LLMManager::setMaxTokens(int v){std::lock_guard<std::mutex> lock(m_mutex);m_defaultMaxTokens=std::clamp(v,1,4096);for(auto& p:m_modelStates)p.second.maxTokens=m_defaultMaxTokens;}int LLMManager::getMaxTokens()const{std::lock_guard<std::mutex> lock(m_mutex);return m_defaultMaxTokens;}
bool LLMManager::loadModelFromFile(const std::string& n){std::ifstream file(n,std::ios::binary|std::ios::ate);if(!file.good()||file.tellg()<=0)return false;auto backend=createLlamaCppBackend();if(!backend||!backend->load(n))return false;ModelState state;state.loaded=true;state.temperature=m_defaultTemperature;state.topP=m_defaultTopP;state.maxTokens=m_defaultMaxTokens;state.backend=std::move(backend);m_modelStates[n]=std::move(state);return true;}
void LLMManager::unloadModelInternal(const std::string& n){auto it=m_modelStates.find(n);if(it!=m_modelStates.end()&&it->second.backend)it->second.backend->unload();}
void LLMManager::initializeAvailableModels(){std::lock_guard<std::mutex> lock(m_mutex);m_availableModels.clear();m_availableModels.push_back({"qwen3-0.6b-q4","","GGUF","Q4","","Qwen","",0,0,{"en","ur","hi","ar"},false,false,false});m_availableModels.push_back({"qwen3-1.7b-q4","","GGUF","Q4","","Qwen","",0,0,{"en","ur","hi","ar"},false,false,false});m_availableModels.push_back({"qwen3-4b-q4","","GGUF","Q4","","Qwen","",0,0,{"en","ur","hi","ar"},false,false,false});}
