package com.livehumanai.livehumanai.ui.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.livehumanai.livehumanai.data.repository.AIRepository
import com.livehumanai.livehumanai.data.repository.ConversationRepository
import com.livehumanai.livehumanai.data.repository.MemoryRepository
import com.livehumanai.livehumanai.data.repository.ModelRepository
import com.livehumanai.livehumanai.data.repository.SettingsRepository
import com.livehumanai.livehumanai.jalebi.JalebiCameraAnalyzer
import com.livehumanai.livehumanai.jalebi.JalebiLiveController
import com.livehumanai.livehumanai.jalebi.JalebiTelemetry
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import org.json.JSONObject
import javax.inject.Inject

@HiltViewModel
class AIViewModel @Inject constructor(private val aiRepository: AIRepository,private val conversationRepository:ConversationRepository,private val memoryRepository:MemoryRepository,private val modelRepository:ModelRepository,private val settingsRepository:SettingsRepository,private val jalebiLiveController:JalebiLiveController):ViewModel(){
 private val _aiState=MutableStateFlow<AIState>(AIState.Idle);val aiState:StateFlow<AIState> = _aiState.asStateFlow();private val _currentConversationId=MutableStateFlow<Long?>(null);val currentConversationId:StateFlow<Long?>=_currentConversationId.asStateFlow();private val _performanceMetrics=MutableStateFlow(PerformanceMetrics());val performanceMetrics:StateFlow<PerformanceMetrics>=_performanceMetrics.asStateFlow();private val _loadedModels=MutableStateFlow<List<String>>(emptyList());val loadedModels:StateFlow<List<String>>=_loadedModels.asStateFlow();private val _jclTelemetry=MutableStateFlow(JalebiTelemetry());val jclTelemetry:StateFlow<JalebiTelemetry>=_jclTelemetry.asStateFlow()
 init{if(!aiRepository.initialize())_aiState.value=AIState.Error("Failed to initialize AI runtime");viewModelScope.launch{settingsRepository.initializeDefaultSettings()};startPerformanceMonitoring()};override fun onCleared(){jalebiLiveController.stop();aiRepository.shutdown();super.onCleared()}
 fun generateResponse(prompt:String,conversationId:Long?=null,modelName:String=""){viewModelScope.launch{try{_aiState.value=AIState.Thinking;val r=aiRepository.generate(prompt,modelName,settingsRepository.getTemperature(),settingsRepository.getMaxTokens());conversationId?.let{conversationRepository.addMessageToConversation(it,r,false)};_aiState.value=AIState.Response(r)}catch(e:Exception){_aiState.value=AIState.Error(e.message?:"Unknown error")}}};fun stopGeneration(){aiRepository.stopGeneration();_aiState.value=AIState.Idle}
 fun startJalebiLoop(goal:String,maxIterations:Int=8):Boolean{val id=jalebiLiveController.start(goal,maxIterations)?:run{_jclTelemetry.value=_jclTelemetry.value.copy(state="FAILED");return false};refreshJalebiLoop(id,goal);return true};fun startLiveJalebi(goal:String="Continuously understand the current user context",maxIterations:Int=8)=startJalebiLoop(goal,maxIterations)
 fun submitLivePerception(input:String,evaluation:suspend(String)->JalebiLiveController.Evaluation){jalebiLiveController.submitPerception(input,evaluation);viewModelScope.launch{delay(25);refreshJalebiLoop()}}
 fun submitJalebiCameraFrame(frame:JalebiCameraAnalyzer.FrameSignal){if(jalebiLiveController.currentLoopId()==null)return;submitLivePerception("camera frame ${frame.timestampMs} checksum=${frame.checksum}"){val raw=aiRepository.analyzeVisionRgba(frame.rgba,frame.width,frame.height,aiRepository.getRecommendedVisionModel());val json=runCatching{JSONObject(raw)}.getOrNull();val scene=json?.optString("sceneId","camera")?:"camera";val confidence=json?.optDouble("confidence",0.0)?.toFloat()?.coerceIn(0f,1f)?:0f;val objects=mutableListOf<String>();json?.optJSONArray("objects")?.let{a->for(i in 0 until a.length())objects+=a.optString(i)};val text=mutableListOf<String>();json?.optJSONArray("text")?.let{a->for(i in 0 until a.length())text+=a.optString(i)};val tool=jalebiLiveController.currentLoopId()?.let{id->aiRepository.submitJalebiVision(id,scene,objects,text,confidence)}?:"";JalebiLiveController.Evaluation(confidence,false,"scene=$scene objects=${objects.joinToString()} text=${text.joinToString()} tool=$tool",if(confidence<.9f)"Re-perceive scene" else "Wait for meaningful scene change")}}
 fun stopLiveJalebi(){jalebiLiveController.stop();_jclTelemetry.value=_jclTelemetry.value.copy(state="CANCELLED",loopId=null)};fun pauseJalebiLoop(){jalebiLiveController.pause();refreshJalebiLoop()};fun resumeJalebiLoop(){jalebiLiveController.resume();refreshJalebiLoop()};fun replanJalebiLoop(reason:String="manual_replan"){jalebiLiveController.currentLoopId()?.let{id->aiRepository.replanJalebiLoop(id,reason);refreshJalebiLoop(id)}};fun executeJalebiIteration(input:String){jalebiLiveController.currentLoopId()?.let{id->aiRepository.executeJalebiIteration(id,input);refreshJalebiLoop(id)}};fun evaluateJalebiLoop(confidence:Float,goalCompleted:Boolean,evaluation:String,nextAction:String,memoryUpdates:String=""){jalebiLiveController.currentLoopId()?.let{id->aiRepository.evaluateAndReplanIfNeeded(id,confidence,goalCompleted,evaluation,nextAction,memoryUpdates);refreshJalebiLoop(id)}}
 fun generateWithConfidenceEscalation(prompt:String,modelName:String=aiRepository.getRecommendedLLMModel(),threshold:Float=.9f,maxEscalations:Int=2,maxTokens:Int=512,confidence:(String,String)->Float){viewModelScope.launch{try{_aiState.value=AIState.Thinking;val r=aiRepository.generateWithConfidenceEscalation(prompt,modelName,threshold,maxEscalations,maxTokens,confidence);_aiState.value=if(r.verified)AIState.Response(r.answer)else AIState.Error("AI result could not be verified");refreshJalebiLoop()}catch(e:Exception){_aiState.value=AIState.Error(e.message?:"Confidence escalation failed")}}}
 fun evaluateAndReplanIfNeeded(confidence:Float,goalCompleted:Boolean,evaluation:String,nextAction:String,memoryUpdates:String=""){jalebiLiveController.currentLoopId()?.let{id->aiRepository.evaluateAndReplanIfNeeded(id,confidence,goalCompleted,evaluation,nextAction,memoryUpdates);refreshJalebiLoop(id)}}
 fun refreshJalebiLoop(loopId:Int?=jalebiLiveController.currentLoopId(),goal:String=_jclTelemetry.value.goal){loopId?:return;_jclTelemetry.value=_jclTelemetry.value.copy(state=aiRepository.getJalebiLoopState(loopId),iteration=aiRepository.getJalebiIteration(loopId),confidence=aiRepository.getJalebiConfidence(loopId),loopId=loopId,goal=goal,ramPercent=aiRepository.getRAMUsagePercentage(),temperatureC=aiRepository.getTemperature(),historyJson=aiRepository.getJalebiHistory(loopId),model=aiRepository.getRecommendedLLMModel())}
 suspend fun createNewConversation(title:String="New Conversation"):Long=conversationRepository.createConversation(title).also{_currentConversationId.value=it};suspend fun getConversation(conversationId:Long){_currentConversationId.value=conversationRepository.getConversationById(conversationId).first?.id};suspend fun addMessageToConversation(content:String,isUser:Boolean){_currentConversationId.value?.let{conversationRepository.addMessageToConversation(it,content,isUser)}};fun loadModel(modelName:String){viewModelScope.launch{if(aiRepository.loadModel(modelName))_loadedModels.value+=modelName}};fun unloadModel(modelName:String){viewModelScope.launch{if(aiRepository.unloadModel(modelName))_loadedModels.value=_loadedModels.value-modelName}};suspend fun remember(content:String,title:String?=null){memoryRepository.createMemory(content=content,title=title,isImportant=true)};suspend fun searchMemories(query:String)=memoryRepository.searchMemories(query).map{it.content};suspend fun getPerformanceMode()=settingsRepository.getPerformanceMode();suspend fun setPerformanceMode(mode:String)=settingsRepository.setPerformanceMode(mode)
 private fun startPerformanceMonitoring()=viewModelScope.launch(Dispatchers.Default){while(true){_performanceMetrics.value=PerformanceMetrics(aiRepository.getCPUUsage(),aiRepository.getRAMUsagePercentage(),aiRepository.getTemperature(),aiRepository.getBatteryLevel(),aiRepository.getTotalRAM(),aiRepository.getAvailableRAM());if(jalebiLiveController.isRunning())refreshJalebiLoop();delay(1000)}}
 sealed class AIState{data object Idle:AIState();data object Thinking:AIState();data class Response(val text:String):AIState();data class Error(val message:String):AIState()};data class PerformanceMetrics(val cpuUsage:Float=0f,val ramUsage:Float=0f,val temperature:Float=0f,val batteryLevel:Float=0f,val totalRAM:Long=0,val availableRAM:Long=0)
}
