#include "VisionManager.h"
#include <algorithm>
#include <fstream>
VisionManager::VisionManager(){initializeAvailableModels();} VisionManager::~VisionManager(){shutdown();}
bool VisionManager::initialize(){initializeAvailableModels();return true;} void VisionManager::shutdown(){std::lock_guard<std::mutex> lock(m_mutex);for(auto& p:m_modelStates)if(p.second.backend)p.second.backend->unload();m_modelStates.clear();m_loadedModels.clear();}
bool VisionManager::loadModel(const std::string& n){std::lock_guard<std::mutex> lock(m_mutex);if(n.empty())return false;if(m_modelStates.count(n)&&m_modelStates.at(n).loaded)return true;return loadModelFromFile(n);} bool VisionManager::unloadModel(const std::string& n){std::lock_guard<std::mutex> lock(m_mutex);auto it=m_modelStates.find(n);if(it==m_modelStates.end())return false;if(it->second.backend)it->second.backend->unload();m_modelStates.erase(it);m_loadedModels.erase(std::remove(m_loadedModels.begin(),m_loadedModels.end(),n),m_loadedModels.end());return true;}
bool VisionManager::isModelLoaded(const std::string& n)const{std::lock_guard<std::mutex> lock(m_mutex);auto it=m_modelStates.find(n);return it!=m_modelStates.end()&&it->second.loaded&&it->second.backend&&it->second.backend->isLoaded();} std::vector<std::string> VisionManager::getLoadedModels()const{std::lock_guard<std::mutex> lock(m_mutex);return m_loadedModels;}
std::vector<std::string> VisionManager::detectObjects(const cv::Mat& image,const std::string& n){std::lock_guard<std::mutex> lock(m_mutex);std::string s=n.empty()?(m_loadedModels.empty()?std::string{}:m_loadedModels.front()):n;auto it=m_modelStates.find(s);if(s.empty()||it==m_modelStates.end()||!it->second.backend||!it->second.backend->isLoaded())return{};std::vector<std::string> out;for(const auto& d:it->second.backend->detectObjects(image))if(d.confidence>=0.0f&&!d.label.empty())out.push_back(d.label);return out;}
std::vector<std::string> VisionManager::detectFaces(const cv::Mat& image,const std::string& n){std::lock_guard<std::mutex> lock(m_mutex);std::string s=n.empty()?(m_loadedModels.empty()?std::string{}:m_loadedModels.front()):n;auto it=m_modelStates.find(s);if(s.empty()||it==m_modelStates.end()||!it->second.backend||!it->second.backend->isLoaded())return{};std::vector<std::string> out;for(const auto& d:it->second.backend->detectFaces(image))if(!d.label.empty())out.push_back(d.label);return out;}
std::string VisionManager::detectText(const cv::Mat& image,const std::string& n){std::lock_guard<std::mutex> lock(m_mutex);std::string s=n.empty()?(m_loadedModels.empty()?std::string{}:m_loadedModels.front()):n;auto it=m_modelStates.find(s);if(s.empty()||it==m_modelStates.end()||!it->second.backend||!it->second.backend->isLoaded())return{};return it->second.backend->detectText(image);}
std::string VisionManager::analyzeScene(const cv::Mat& image,const std::string& n){std::lock_guard<std::mutex> lock(m_mutex);std::string s=n.empty()?(m_loadedModels.empty()?std::string{}:m_loadedModels.front()):n;auto it=m_modelStates.find(s);if(s.empty()||it==m_modelStates.end()||!it->second.backend||!it->second.backend->isLoaded())return{};return it->second.backend->analyzeScene(image);}
VisionManager::ModelInfo VisionManager::getModelInfo(const std::string& n)const{std::lock_guard<std::mutex> lock(m_mutex);for(const auto& m:m_availableModels)if(m.name==n)return m;return{};} std::vector<VisionManager::ModelInfo> VisionManager::getAvailableModels()const{std::lock_guard<std::mutex> lock(m_mutex);return m_availableModels;} float VisionManager::benchmarkModel(const std::string& n){return isModelLoaded(n)?0.0f:0.0f;} cv::Mat VisionManager::preprocessImage(const cv::Mat& image){return image.clone();}
bool VisionManager::loadModelFromFile(const std::string& n){std::ifstream file(n,std::ios::binary|std::ios::ate);if(!file.good()||file.tellg()<=0)return false;auto backend=createOnnxVisionBackend();if(!backend||!backend->load(n))return false;ModelState state;state.loaded=true;state.backend=std::move(backend);m_modelStates[n]=std::move(state);m_loadedModels.push_back(n);return true;} void VisionManager::unloadModelInternal(const std::string& n){auto it=m_modelStates.find(n);if(it!=m_modelStates.end()&&it->second.backend)it->second.backend->unload();}
void VisionManager::initializeAvailableModels(){std::lock_guard<std::mutex> lock(m_mutex);m_availableModels.clear();m_availableModels.push_back({"yolo-nano","1.0",0,"ONNX","object_detection",{"object_detection"},"","","",false});m_availableModels.push_back({"mobilenet-v3","1.0",0,"ONNX","image_classification",{"image_classification"},"","","",false});m_availableModels.push_back({"ocr-lightweight","1.0",0,"ONNX","ocr",{"ocr","text_detection"},"","","",false});}
